#ifndef TEMPLATE_PROJECT__GENERATED_VERSION_H
#define TEMPLATE_PROJECT__GENERATED_VERSION_H

#define COMPILE_BUILD "__BUILD__"
#define COMPILE_TIMESTAMP "__TIMESTAMP__"

#endif //TEMPLATE_PROJECT__GENERATED_VERSION_H
